version: "3"

volumes:
  python_sock:
  proxy_logs:
  celery:

services:
  proxy:
    restart: unless-stopped
    image: nginx:1.21-alpine
    depends_on:
      - backend
    volumes:
      - ./backend/static:/var/www/backend/static
      - ./backend/media:/var/www/backend/media
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/conf.d:/etc/nginx/conf.d:ro
      - proxy_logs:/var/log/nginx
      - python_sock:/var/run/python

  backend:
    restart: unless-stopped
    image: parser/backend
    build:
      context: ./docker/backend
    depends_on:
      - db
      - redis
      - webdriver
    volumes:
      - ./backend:/var/www/backend
      - python_sock:/var/run/python
      - celery:/var/www/celery
    env_file:
      - .env

  db:
    restart: unless-stopped
    image: mariadb
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/data:/var/lib/mysql
    env_file:
      - .env

  redis:
    restart: unless-stopped
    image: redis:6-alpine

  webdriver:
    image: selenium/standalone-chrome
    shm_size: '1gb'
    restart: on-failure
