# Generated by Django 3.2.6 on 2022-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220512_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='ParsingResult',
        ),
        migrations.RemoveIndex(
            model_name='parsingresult',
            name='main_result_hash_c2e898_idx',
        ),
        migrations.AddIndex(
            model_name='parsingresult',
            index=models.Index(fields=['hash'], name='main_parsin_hash_927234_idx'),
        ),
    ]
