# Generated by Django 3.2.6 on 2022-05-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220512_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScriptName',
            new_name='ParserScript',
        ),
        migrations.RenameField(
            model_name='parserscript',
            old_name='script_name',
            new_name='parser_script',
        ),
        migrations.RenameField(
            model_name='parsingjob',
            old_name='script_name',
            new_name='parser_script',
        ),
    ]
